define k = Character(_("Квист"), who_color="#c8c8ff")
define n = Character(_("Нонни"), who_color="#90c8ff")
define l = Character(_("Линь Чи"), who_color="#C5A35E")
define b = Character(_("Беккер"), who_color="#d0a0ff")
define m = Character(_("Микко"), who_color="#a0ffa0")
define a = Character(_("Андреа"), who_color="#ffa0a0")
define i = Character(_("Иво"), who_color="#c0c0c0")
define p = Character(_("Пауль"), who_color="#789F7A")