default clients = {
    "nonni": {
        "name": "Нонни",
        "description": "Держит больницу в городе",
        "phone": True,
        "order_name": "Аппарат диагностики",
        "order_active": True,
        "order_completed": False,
        "repair_day": None,
        "repair_price": None,
        "called": 0,
        "wine_offered": False,     
        "wine_accepted": False,  
        "wine_complete": False,
        "banned": False,
        "foreverbanned": False,
    },
    "linh": {
        "name": "Линь Чи",
        "description": "Пожилая женщина.",
        "phone": False,
        "order_name": "Плеер",
        "order_active": False,
        "order_completed": False,
        "repair_day": None,
        "repair_price": None,
        "called": 0,
        "burned" : False
    },
    "bekker": {
        "name": "Беккер",
        "description": "Поставщик деталей",
        "phone": True,
        "order_name": "Модуль магнитного самоката",  
        "order_active": False,
        "order_completed": False,
        "repair_day": None,
        "repair_price": None,
        "ordered_part": None,   
        "called": 0,
        "base_price": 7,
        "banned": False,
        "foreverbanned": False
    },
    "mikko": {
        "name": "Микко",
        "description": "Старый друг.",
        "phone": True,
        "called": 0,         
        "hangouts": 0,
        "hangouts_day_1": False,
        "hangouts_day_2": False,
        "hangouts_day_3": False,
        "calls_per_week": 0,
        "banned": False,
        "is_called": False
    },
    "ivo": {
        "name": "Иво",
        "description": "Специалист по взлому компов",
        "phone": False,
        "order_name": "Браслет комуникатора",  
        "order_active": False,
        "order_completed": False,
        "repair_day": None,
        "repair_price": None,
        "banned": False,
        "called": 0, 
    },
     "andrea": {
        "name": "Андреа",
        "description": "Дочь Квиста...",
        "called": 0,
        "takeaway": False,
        "cure_price": 20,
        "nonni_delivered": False,
        "medicine_bought": False
    },
    "pol": {
        "name": "Пол",
        "made_raid": False,
        "base_price": 20,
        "hacked": False,
        "get_jailed": False
    },
}