# define k = Character(_("Kvist"), who_color="#c8c8ff")
# define n = Character(_("Nonni"), who_color="#90c8ff")
# define l = Character(_("Lin Chi"), who_color="#ffd8b0")
# define b = Character(_("Bekker"), who_color="#d0a0ff")
# define m = Character(_("Mikko"), who_color="#a0ffa0")
# define a = Character(_("Andrea"), who_color="#ffa0a0")
# define i = Character(_("Ivo"), who_color="#c0c0c0")
# define p = Character(_("Paul"), who_color="#c0c0c0")

define k = Character(_("Квист"), who_color="#c8c8ff")
define n = Character(_("Нонни"), who_color="#90c8ff")
define l = Character(_("Линь Чи"), who_color="#ffd8b0")
define b = Character(_("Беккер"), who_color="#d0a0ff")
define m = Character(_("Микко"), who_color="#a0ffa0")
define a = Character(_("Андреа"), who_color="#ffa0a0")
define i = Character(_("Иво"), who_color="#c0c0c0")
define p = Character(_("Пауль"), who_color="#c0c0c0")